### ISSUE TITLE
State of Environment - FY 2018-19 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/soe#9]
- [x] update to latest terriajs

- [x] fix the help button: https://github.com/TerriaJS/soe/pull/8

**Comment by soyarsauce** [comment]
Hey @na9da was there any progress for this? Or any notes for passing to @rowanwins?

**Comment by rowanwins** [comment]
#8 merged

And a new PR created which updates terriajs in #10

**Comment by AnaBelgun** [comment]
pending approval from DoEE

**Comment by AnaBelgun** [comment]
still pending approval as of 21 Jul

**Comment by AnaBelgun** [comment]
Custodian ok to release
